<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>synthgen</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SynthGen.Core\SynthGen.Core.csproj" />
  </ItemGroup>

</Project>
