using System.Globalization;
using System.Text;
using SynthGen.Core.Model;

namespace SynthGen.Core.Rules;

/// <summary>
/// Produces a starter rules YAML from a parsed table definition. The output is
/// hand-rendered (not serialized) so every column carries a comment describing
/// the DDL it was inferred from.
/// </summary>
public static class RuleScaffolder
{
    public static string Scaffold(TableDefinition table, int rows = 100, int? seed = 12345)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Rules for {table.Schema}.{table.Name} — generated by 'synthgen init'.");
        sb.AppendLine("# Every entry was inferred from the DDL; adjust strategies, ranges and rates as needed.");
        sb.AppendLine("# Strategies: skip, dbDefault, int, decimal, bool, date, datetime, time, guid,");
        sb.AppendLine("#             string, bytes, template, pick, sequence, faker, query, constant.");

        if (table.CheckConstraints.Count > 0)
        {
            sb.AppendLine("#");
            sb.AppendLine("# CHECK constraints found in the DDL. The generator does not enforce these");
            sb.AppendLine("# automatically — encode them in the rules below and verify with evaluations:");
            foreach (var check in table.CheckConstraints)
                sb.AppendLine($"#   {(check.Name is null ? "" : check.Name + ": ")}{check.Expression}");
        }

        sb.AppendLine();
        sb.AppendLine($"table: {table.Schema}.{table.Name}");
        sb.AppendLine($"rows: {rows}");
        if (seed is not null) sb.AppendLine($"seed: {seed}");
        sb.AppendLine("truncateBeforeLoad: false");
        sb.AppendLine("batchSize: 10000");
        sb.AppendLine();
        sb.AppendLine("columns:");

        foreach (var col in table.Columns)
        {
            var rule = ColumnInference.Infer(col, table);
            sb.AppendLine($"  # {DescribeColumn(col, table)}");
            sb.AppendLine($"  {col.Name}:");
            AppendRule(sb, rule, indent: "    ");
        }

        sb.AppendLine();
        sb.AppendLine("evaluations:");
        AppendEvaluations(sb, table, rows);
        return sb.ToString();
    }

    private static string DescribeColumn(ColumnDefinition col, TableDefinition table)
    {
        var parts = new List<string> { FormatType(col) };
        if (col.IsIdentity) parts.Add($"IDENTITY({col.IdentitySeed},{col.IdentityIncrement})");
        if (col.IsPrimaryKey) parts.Add("PRIMARY KEY");
        else if (col.HasUniqueConstraint) parts.Add("UNIQUE");
        parts.Add(col.IsNullable ? "NULL" : "NOT NULL");
        if (col.IsComputed) parts.Add("computed");
        if (col.DefaultExpression is not null) parts.Add($"DEFAULT {col.DefaultExpression}");

        var fk = table.ForeignKeys.FirstOrDefault(f =>
            f.Columns.Count == 1 &&
            string.Equals(f.Columns[0], col.Name, StringComparison.OrdinalIgnoreCase));
        if (fk is not null) parts.Add($"FK -> {fk.ReferencedTable}");

        return string.Join(" ", parts);
    }

    private static string FormatType(ColumnDefinition col)
    {
        if (col.Length is not null)
            return $"{col.SqlType}({(col.Length == -1 ? "max" : col.Length.ToString())})";
        if (col.Precision is not null && col.SqlType is "decimal" or "numeric")
            return $"{col.SqlType}({col.Precision},{col.Scale ?? 0})";
        return col.SqlType;
    }

    private static void AppendRule(StringBuilder sb, ColumnRule rule, string indent)
    {
        void Add(string key, object? value)
        {
            if (value is null) return;
            string text = value switch
            {
                bool b => b ? "true" : "false",
                double d => d.ToString(CultureInfo.InvariantCulture),
                string s => NeedsQuoting(s) ? $"'{s.Replace("'", "''")}'" : s,
                _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "",
            };
            sb.AppendLine($"{indent}{key}: {text}");
        }

        Add("strategy", rule.Strategy);
        Add("min", rule.Min);
        Add("max", rule.Max);
        Add("template", rule.Template);
        Add("method", rule.Method);
        Add("query", rule.Query);
        Add("value", rule.Value);
        Add("start", rule.Start);
        Add("step", rule.Step);
        Add("length", rule.Length);
        Add("trueRate", rule.TrueRate);
        Add("nullRate", rule.NullRate);
        Add("unique", rule.Unique);
        if (rule.Values is not null)
            sb.AppendLine($"{indent}values: [{string.Join(", ", rule.Values)}]");
    }

    private static void AppendEvaluations(StringBuilder sb, TableDefinition table, int rows)
    {
        void AddEval(string name, string query, string expectKey, string expectValue)
        {
            sb.AppendLine($"  - name: {name}");
            sb.AppendLine($"    query: '{query.Replace("'", "''")}'");
            sb.AppendLine("    expect:");
            sb.AppendLine($"      {expectKey}: {expectValue}");
        }

        AddEval("row-count", $"SELECT COUNT(*) FROM {table.QualifiedName}", "equals", rows.ToString());

        foreach (var col in table.Columns.Where(c => !c.IsNullable && !c.IsDbGenerated))
        {
            AddEval(
                $"not-null-{col.Name.ToLowerInvariant()}",
                $"SELECT COUNT(*) FROM {table.QualifiedName} WHERE [{col.Name}] IS NULL",
                "equals", "0");
        }

        foreach (var col in table.Columns.Where(c => c.HasUniqueConstraint || (c.IsPrimaryKey && !c.IsIdentity)))
        {
            AddEval(
                $"unique-{col.Name.ToLowerInvariant()}",
                $"SELECT COUNT(*) - COUNT(DISTINCT [{col.Name}]) FROM {table.QualifiedName}",
                "equals", "0");
        }
    }

    private static bool NeedsQuoting(string s) =>
        s.Length == 0 ||
        s.StartsWith(' ') || s.EndsWith(' ') ||
        s.Contains(':') || s.Contains('#') || s.Contains('\'') || s.Contains('"') ||
        s.Contains('{') || s.Contains('[') || s.Contains('<') || s.Contains('>') ||
        s.StartsWith('-') || s.StartsWith('*') || s.StartsWith('&') || s.StartsWith('!');
}
