using System.ComponentModel;
using Dapper;
using Spectre.Console.Cli;
using SynthGen.Core.Sqlite;

namespace SynthGen.Cli.Commands;

/// <summary>
/// Applies the fixed, documented defects used by the AdventureWorks patch demonstration.
/// This is sample-fixture setup, not a patch generator: the repair values still come only
/// from the reviewed gap rules and are frozen by Planner.
/// </summary>
[Description("Apply deterministic AdventureWorks sample corruption for the patch demo.")]
public sealed class AdventureWorksCorruptCommand : Command<AdventureWorksCorruptCommand.Settings>
{
    public sealed class Settings : CommandSettings
    {
        [CommandOption("-c|--connection <PATH>")]
        [Description("SQLite database generated by samples/adventureworks/run-local.ps1.")]
        public string Connection { get; init; } = "";
    }

    protected override int Execute(CommandContext context, Settings settings, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(settings.Connection))
        {
            Console.Error.WriteLine("error: --connection is required.");
            return ExitCodes.ConfigError;
        }

        if (!SqliteNative.TryInitialize(out var error))
        {
            Console.Error.WriteLine($"error: {error}");
            return ExitCodes.ConfigError;
        }

        var factory = new SqliteConnectionFactory(settings.Connection,
            SqliteConnectionFactory.DiscoverSchemas(settings.Connection));
        using var conn = factory.Open();
        conn.Execute("""
            UPDATE [Production].[Product]
            SET [Color] = 'X9'
            WHERE [ProductID] IN (1, 2, 3);

            UPDATE [Sales].[SalesOrderHeader]
            SET [Status] = 0
            WHERE [SalesOrderID] IN (1, 2, 3);

            UPDATE [Sales].[Customer]
            SET [PersonID] = NULL
            WHERE [CustomerID] IN (1, 2, 3);
            """);

        Console.WriteLine("AdventureWorks deterministic corruption applied (product/order/customer ids 1-3).");
        return ExitCodes.Ok;
    }
}
