using System.ComponentModel;
using Dapper;
using Spectre.Console.Cli;
using SynthGen.Core.Sqlite;

namespace SynthGen.Cli.Commands;

/// <summary>
/// Applies the fixed, documented defects used by the AdventureWorks patch demonstration.
/// This is sample-fixture setup, not a patch generator: the repair values still come only
/// from the reviewed gap rules and are frozen by Planner.
/// </summary>
[Description("Apply deterministic AdventureWorks sample corruption for the patch demo.")]
public sealed class AdventureWorksCorruptCommand : Command<AdventureWorksCorruptCommand.Settings>
{
    public sealed class Settings : CommandSettings
    {
        [CommandOption("-c|--connection <PATH>")]
        [Description("SQLite database generated by samples/adventureworks/run-local.ps1.")]
        public string Connection { get; init; } = "";
    }

    protected override int Execute(CommandContext context, Settings settings, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(settings.Connection))
        {
            Console.Error.WriteLine("error: --connection is required.");
            return ExitCodes.ConfigError;
        }

        if (!SqliteNative.TryInitialize(out var error))
        {
            Console.Error.WriteLine($"error: {error}");
            return ExitCodes.ConfigError;
        }

        var factory = new SqliteConnectionFactory(settings.Connection,
            SqliteConnectionFactory.DiscoverSchemas(settings.Connection));
        using var conn = factory.Open();
        conn.Execute("""
            UPDATE [Production].[Product]
            SET [Color] = 'X9'
            WHERE [ProductID] IN (1, 2, 3);

            UPDATE [Sales].[SalesOrderHeader]
            SET [Status] = 0
            WHERE [SalesOrderID] IN (1, 2, 3);

            UPDATE [Sales].[Customer]
            SET [PersonID] = NULL
            WHERE [CustomerID] IN (1, 2, 3);

            -- The D-C3 currency fixture: 14 rows lose their ISO name (CUR-001 repairs
            -- them from datasets/currencies.yaml) and one garbage code the vocabulary
            -- does not know arrives with no name — that row must be SKIPPED at the gate,
            -- never guessed.
            UPDATE [Sales].[Currency]
            SET [Name] = NULL
            WHERE [CurrencyCode] IN (
                SELECT [CurrencyCode] FROM [Sales].[Currency]
                ORDER BY [CurrencyCode] LIMIT 14);

            INSERT INTO [Sales].[Currency] ([CurrencyCode], [Name], [ModifiedDate])
            SELECT 'ZZZ', NULL, '2024-01-01 00:00:00'
            WHERE NOT EXISTS (
                SELECT 1 FROM [Sales].[Currency] WHERE [CurrencyCode] = 'ZZZ');
            """);

        Console.WriteLine("AdventureWorks deterministic corruption applied " +
                          "(product/order/customer ids 1-3; 14 currency names NULLed plus the ZZZ row).");
        return ExitCodes.Ok;
    }
}
